import { exec } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";

const execAsync = promisify(exec);

const TEMPLATES: Record<string, Record<string, string>> = {
	freqtrade: {
		"strategy.py": `# Freqtrade Strategy
class QuantDeskStrategy:
    """Strategy generated by QuantDesk agent."""

    INTERFACE_VERSION = 3
    minimal_roi = {"0": 0.1}
    stoploss = -0.05
    timeframe = "5m"

    def populate_indicators(self, dataframe, metadata):
        return dataframe

    def populate_entry_trend(self, dataframe, metadata):
        return dataframe

    def populate_exit_trend(self, dataframe, metadata):
        return dataframe
`,
		"config.json": JSON.stringify(
			{
				trading_mode: "spot",
				stake_currency: "USDT",
				stake_amount: "unlimited",
				dry_run: true,
				exchange: { name: "binance", key: "", secret: "" },
			},
			null,
			2,
		),
	},
	hummingbot: {
		"strategy.py": `# Hummingbot Strategy
class QuantDeskStrategy:
    """Strategy generated by QuantDesk agent."""
    pass
`,
		"conf_strategy.yml": `# Hummingbot configuration
strategy: pure_market_making
exchange: binance
market: BTC-USDT
bid_spread: 0.001
ask_spread: 0.001
order_amount: 0.01
`,
	},
	nautilus: {
		"strategy.py": `# Nautilus Trader Strategy
class QuantDeskStrategy:
    """Strategy generated by QuantDesk agent."""
    pass
`,
		"config.py": `# Nautilus Trader configuration
from nautilus_trader.config import StrategyConfig

config = StrategyConfig(
    strategy_id="QuantDesk-001",
)
`,
	},
	generic: {
		"README.md": `# QuantDesk generic workspace

Agent-written strategy. No engine template — the agent writes both
the strategy and the backtest/live scripts from scratch.
`,
	},
};

async function git(cwd: string, ...args: string[]): Promise<string> {
	const { stdout } = await execAsync(`git ${args.join(" ")}`, { cwd });
	return stdout.trim();
}

export async function initWorkspace(
	deskId: string,
	engine: string,
	workspacesRoot: string,
): Promise<string> {
	const dir = join(workspacesRoot, deskId);
	await mkdir(dir, { recursive: true });

	await git(dir, "init");
	await git(dir, "config", "user.email", '"quantdesk@local"');
	await git(dir, "config", "user.name", '"QuantDesk"');

	const template = TEMPLATES[engine] ?? TEMPLATES.generic!;
	for (const [filename, content] of Object.entries(template)) {
		await writeFile(join(dir, filename), content);
	}

	await git(dir, "add", "-A");
	await git(dir, "commit", "-m", '"Initial workspace setup"');

	return dir;
}

export async function commitCode(cwd: string, message: string): Promise<string> {
	await git(cwd, "add", "-A");
	await git(cwd, "commit", "-m", `"${message.replace(/"/g, '\\"')}"`);
	const hash = await git(cwd, "rev-parse", "HEAD");
	return hash;
}

export async function getCode(cwd: string, commitHash: string, filePath: string): Promise<string> {
	const { stdout } = await execAsync(`git show ${commitHash}:${filePath}`, { cwd });
	return stdout;
}

export async function getDiff(cwd: string, hash1: string, hash2: string): Promise<string> {
	return git(cwd, "diff", hash1, hash2);
}

export async function hasChanges(cwd: string): Promise<boolean> {
	const status = await git(cwd, "status", "--porcelain");
	return status.length > 0;
}

export interface CommitInfo {
	hash: string;
	message: string;
	date: string;
}

export async function getLog(cwd: string, limit = 50): Promise<CommitInfo[]> {
	const raw = await git(cwd, "log", `--max-count=${limit}`, "--format=%H%n%s%n%aI%n---");
	if (!raw) return [];
	const commits: CommitInfo[] = [];
	const entries = raw.split("---").filter((s) => s.trim());
	for (const entry of entries) {
		const lines = entry.trim().split("\n");
		if (lines.length >= 3) {
			commits.push({ hash: lines[0]!, message: lines[1]!, date: lines[2]! });
		}
	}
	return commits;
}

export async function listFiles(cwd: string, commitHash?: string): Promise<string[]> {
	const ref = commitHash ?? "HEAD";
	const raw = await git(cwd, "ls-tree", "-r", "--name-only", ref);
	if (!raw) return [];
	return raw.split("\n").filter((s) => s.trim());
}
